export const GOOD_PERSON = [
  {
    id: 1,
    name: 'Van Helsing',
    image: '../assetes/images-person/good-person/good-person_1.png',
    health: 220,
    attacket: 25,
    critical_damage: 10,
  },
  {
    id: 2,
    name: 'Leonid',
    image: '../assetes/images-person/good-person/good-person_2.png',
    health: 250,
    attacket: 15,
    critical_damage: 15,
  },
  {
    id: 3,
    name: 'Assassin',
    image: '../assetes/images-person/good-person/good-person_3.jpg',
    health: 230,
    attacket: 40,
    critical_damage: 30,
  },
  {
    id: 4,
    name: 'Witcher',
    image: '../assetes/images-person/good-person/good-person_4.png',
    health: 240,
    attacket: 30,
    critical_damage: 15,
  },
  {
    id: 5,
    name: 'Ninja',
    image: '../assetes/images-person/good-person/good-person_5.png',
    health: 200,
    attacket: 25,
    critical_damage: 35,
  },
  {
    id: 6,
    name: 'Shadow ninja',
    image: '../assetes/images-person/good-person/good-person_6.png',
    health: 220,
    attacket: 35,
    critical_damage: 35,
  },
  {
    id: 7,
    name: 'Valkyrie',
    image: '../assetes/images-person/good-person/good-person_7.png',
    health: 240,
    attacket: 30,
    critical_damage: 15,
  },
  {
    id: 8,
    name: 'Archer',
    image: '../assetes/images-person/good-person/good-person_8.png',
    health: 190,
    attacket: 45,
    critical_damage: 40,
  },
]